### ISSUE TITLE
acorn-jsx could be an extension of acorn?

### ISSUE THREAD

**Issue by angelozerr** [RReverser/acorn-jsx#20]
@RReverser I create this issue because I know you are working on official acorn. acorn-jsx is a copy/paste of the official acorn, but I tell me if acorn-jsx could extend acorn to customize it to support jsx in order to use last source of acorn.

I would like to provide a tern plugin for React inside Eclipse with https://github.com/angelozerr/tern.java but for that I need your work with acorn-jsx.

**Comment by sebmck** [comment]
A port of `acorn-jsx` as an acorn 1.0.0 plugin is available from the [jsx](https://github.com/marijnh/acorn/tree/jsx) branch in `marijnh/acorn`.

**Comment by angelozerr** [comment]
Very cool! Many thank's @sebmck !

**Comment by angelozerr** [comment]
Perhaps you should set the link https://github.com/marijnh/acorn/tree/jsx in the README of acorn-jsx?
