### ISSUE TITLE
`export default <Somejsx />` doesn't parse

### ISSUE THREAD

**Issue by jmm** [RReverser/acorn-jsx#25]
Sorry if I'm missing something obvious, but is there a reason [this](https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=export%20default%20%3CSomejsx%20%2F%3E%3B) shouldn't parse?:

```js
export default <Somejsx />;
```

[This](https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=export%20default%20(%3CSomejsx%20%2F%3E)%3B) does:

```js
export default (<Somejsx />);
```

Same result with `acorn-jsx@2.0.0`, with this of course:
```js
{
  ecmaVersion: 6,
  sourceType: "module",
  plugins: {
    jsx: true
  }
}
```

**Comment by RReverser** [comment]
This is not related to acorn-jsx but an issue in Acorn itself, as it doesn't set `exprAllowed = true` after `export default` and thus cannot handle ambigous cases.

JSX tags are implemented in similar manner as regular expressions (both start with character that is usually tokenized as an operator), and thus it's the same bug - as you can try, `export default /regex/` throws the same error in Acorn.

Please report to the upstream instead and I'll try to look into it when find some time (or you can try on your own).

**Comment by jmm** [comment]
Ah, ok, thanks. I didn't realize it was more general. Reported at https://github.com/marijnh/acorn/issues/283.

>  I'll try to look into it when find some time (or you can try on your own).

Thanks! And thanks for the pointers. I wanted to look into it, but my ability to debug is hampered right now by my [`node-inspector` not working](https://github.com/node-inspector/node-inspector/issues/671).
