### ISSUE TITLE
Support for acorn_loose

### ISSUE THREAD

**Issue by angelozerr** [RReverser/acorn-jsx#32]
It should be cool if acorn-jsx could support acorn_loose to give the capability to parse JSX which is not well formatted to use it for completion with https://github.com/angelozerr/tern-react

**Comment by RReverser** [comment]
Huh, well, it would be, but not too easy given that JSX can contain multiline arbitrary content and you rarely know the original intent/formatting. I tried at some point, but then gave it up. Feel free to PR if you want to work on it.

**Comment by angelozerr** [comment]
If you cannot support that, I will not available to do that -(

Hope a guy could implement acorn_losse one day to benefit with completion with React/JSX.

Thanks for your answer.

**Comment by RReverser** [comment]
It was here https://github.com/RReverser/acorn-jsx/commit/e0bcfca03f8b044de2f23306c18f431d3d578c9a and around just in case you're interested.
