### ISSUE TITLE
License violation test/test-jsx.js

### ISSUE THREAD

**Issue by bastien-roucaries** [RReverser/acorn-jsx#68]
This test file is not under your copyright.

You violate the original BSD license by not adding license header on this test file.

Could you please do it

Bastien for the debian project

**Comment by RReverser** [comment]
Can you send a PR with suggested license header? I'm not sure how it should look like.

**Comment by bastien-roucaries** [comment]
test-jsx is from facebook jsx. So copy verbatim the license and add to it as an header
