### ISSUE TITLE
Support JSXText node

### ISSUE THREAD

**Issue by soda0289** [RReverser/acorn-jsx#73]
The Facebook JSX AST spec has recently changed. They now use `JSXText` nodes instead of `Literal` nodes to store strings inside of `JSXElement` nodes.
https://github.com/facebook/jsx/blob/master/AST.md#jsx-text

This would be a breaking change, if `Literal` was changed to `JSXText`, but would allow this plugin to generate an AST that is more consistent with Babylon, Flow and ESPrima.

@RReverser 
Is this something that you would consider changing?

**Comment by RReverser** [comment]
👍 Can you please submit a PR so that it would go into new major release?

**Comment by soda0289** [comment]
Sure, will work on this tomorrow

**Comment by soda0289** [comment]
It was pretty simple change I just used the same code for the literal nodes in acorn.
https://github.com/RReverser/acorn-jsx/pull/74

**Comment by RReverser** [comment]
Published a new major version.
