### ISSUE TITLE
ASI fails on a variable declaration followed by JSXElement 

### ISSUE THREAD

**Issue by touzoku** [RReverser/acorn-jsx#78]
This parses fine:
```javascript
var foo = {};
<TodoList someprop="someval" />
```

This fails:
```javascript
var foo = {}
<TodoList someprop="someval" />
```
with the following exception:
```
./node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2223
    throw err
    ^

SyntaxError: Unexpected token (2:10)
```

Both cases should either fail or parse at the same time. But it does not seem like an easy fix might exist to this with a recursive-descent parser like acorn, since the grammar is ambiguous without a significant lookahead.

**Comment by RReverser** [comment]
This is an interesting case, thanks.

Although JSX does not have explicit ASI semantics for its own operators, normal ECMAScript grammar still applies, which means ASI should kick in only when without it a syntax error would happen.

The case above with `<` is similar to `/` ambiguity at the beginning of the line, and so I believe this behaviour is actually correct. Consider the following example:

```js
var foo = {};
/TodoList/
```

vs

```jsx
var foo = {}
/TodoList/
```

In both cases, only explicit semicolon can turn an operator such as `/` or `<` into a beginning of an expression, which makes the following content to be parsed differently - division vs regex or less-than vs start element.

Does this make sense?

**Comment by touzoku** [comment]
The aforementioned grammar is only ambiguous for the L0 parser (aka tokenizer). For the G1 parser (aka recognizer) it is an easy job to produce a valid parse tree. The grammar is only ambiguous when the parse could produce two or more parse trees. In both cases above there will be a syntax error, i.e. zero parse trees.

The example below gives you an example of really ambiguous grammar that even G1 parser will fail to recognize without additional semantics. This is from C++:
```c
x * y(z);
```
Here, without knowing the semantics, you don't know if `y(z)` is a pointer of type `x`, or an operand of `x` times `y(z)`. 

The whole situation above would not exist if `acorn` did not use a simple rec-descent algorithm, but let's say an [Earley algorithm](http://jeffreykegler.github.io/Ocean-of-Awareness-blog/). Well, maybe, it is a bit too late for this.

In order to fix the issue, `acorn-jsx` must always parse `<` as `tt.jsxTagStart` without switching the context, and then patch the `parseExprOp` function to perform lookahead for the following tokens — up until the point where the ambiguity is resolved. I'll try to fix it myself, because I have a real customer code where it fails, but this is going to be a messy rewrite...

By the way, it would be nice to add the original `acorn` test fixtures to `acorn-jsx`, since there is a regression on the following tests of original `acorn` due to improper opening angle bracket handling:
```javascript
<!-- HTML comment
<!--\n;
;\n--> HTML comment
```

**Comment by RReverser** [comment]
> since there is a regression on the following tests of original acorn due to improper opening angle bracket handling

Yeah, thanks, it was earlier reported in #41 and already fixed - make sure you're using the latest `acorn-jsx` version.

**Comment by RReverser** [comment]
I'll close this for now, if you wish, you can open a discussion on the JSX specification repo instead.

**Comment by touzoku** [comment]
Thanks for explanation, it makes sense.

My humble opinion is that "one parse tree is better than no tree", but I agree that if majority of parsers in the JS industry follow the same convention it will do more harm than good to change it.

My original point was that under current ASI rules the semicolon would have been inserted if the tokenizer was producing `tt.jsxTagStart` instead of `tt.relational`, because the following condition would be met: 
> The offending token is separated from the previous token by at least one LineTerminator

However, the tokenizer uses a naive algorithm for `<` parsing (this is why you had to add one more condition to the `readToken` function to handle HTML comments properly). My point was that if the tokenizer used a smarter algorithm, i.e. a "[Longest Acceptable Token Match](https://www.youtube.com/watch?v=XaScLywH2CI)", then ASI would kick in and a valid syntax tree would have been produced. Right now, the offending token happens two tokens further down the input stream, this is why ASI can not be applied, when technically it is possible.

Btw, I'm using your plugin to parse something else (not JSX), so this is why I keep coming up with weird cases.
