### ISSUE TITLE
JSXFragment has properties `openingFragment` and `closingFragment`, not `openingElement` and `closingElement`

### ISSUE THREAD

**Issue by adrianheine** [RReverser/acorn-jsx#85]
I actually overlooked that #84 changed the type of the property value, but not the name of the property. `JSXFragment`s should indeed have properties `openingFragment` and `closingFragment`, not `openingElement` and `closingElement`, see https://github.com/facebook/jsx/blob/master/AST.md#jsx-fragment.

**Comment by RReverser** [comment]
Will you send a PR please?
