### ISSUE TITLE
add support for react fragments shot syntax

### ISSUE THREAD

**Issue by ukari** [RReverser/acorn-jsx#96]
for example
``` jsx
let a = () => (
  <>
    <div>A</div>
    <div>B</div>
    <div>C</div>
  </>
);
```

react fragments shot syntax is the snippet(`<></>`) above

[introduce link](https://reactjs.org/docs/fragments.html#short-syntax)

**Comment by RReverser** [comment]
If this is a bug report, can you provide reproduction steps - how you're using it, what error you're getting etc.?

**Comment by ukari** [comment]
Sorry for my mistake, I has been realized it provides a type: "JSXFragment" just now. Closed
