### ISSUE TITLE
Issues in IE11 with untranspiled export

### ISSUE THREAD

**Issue by Scoutski** [RReverser/acorn-jsx#98]
Hi, I just wanted to ask whether or not it would be possible to fully transpile the acorn-jsx export to IE friendly ES5 as it contains a class declaraction (line 72) `return class extends Parser {` that when included in an IE11 project, causes IE11 to fail? If you're happy for me to, I can create a PR to do this?

If you want, I can provide more info. Regardless, I appreciate your time and work, thanks.

**Comment by RReverser** [comment]
Yes, it should be possible, just configure your transpiler to include Acorn-JSX.

**Comment by dmt0** [comment]
I'm using `https://github.com/AndersDJohnson/webpack-babel-env-deps` to determine which packages to transpile to ES5. `acorn-jsx` escapes it (and had to be added manually), since there's no `engines` field in `package.json`. Would be great if things would "just work". 🙂
